version: "3.8"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ariane-bot
    env_file: .env
    restart: unless-stopped
    command: python3 main.py
    volumes:
      - .:/app  # Mounts local directory to /app in the container
    ports:
      - "8080:8080"  # Example port (optional)
